// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3t4cUdC7Mu_C0Zw2EfOpVrmVXcEMrtIo',
    appId: '1:779421460538:web:be21386390906839fbed03',
    messagingSenderId: '779421460538',
    projectId: 'partybox-98bce',
    authDomain: 'partybox-98bce.firebaseapp.com',
    storageBucket: 'partybox-98bce.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtp_A4D1enVeSSlChOG1eXLRlL_7xJok4',
    appId: '1:779421460538:android:f84f23abfd1634cdfbed03',
    messagingSenderId: '779421460538',
    projectId: 'partybox-98bce',
    storageBucket: 'partybox-98bce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5z6Eh_4Rhcggh0zldls7OStFTpvYNpbo',
    appId: '1:779421460538:ios:bb2c7a7d050812a1fbed03',
    messagingSenderId: '779421460538',
    projectId: 'partybox-98bce',
    storageBucket: 'partybox-98bce.firebasestorage.app',
    iosBundleId: 'com.example.actionVerite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5z6Eh_4Rhcggh0zldls7OStFTpvYNpbo',
    appId: '1:779421460538:ios:bb2c7a7d050812a1fbed03',
    messagingSenderId: '779421460538',
    projectId: 'partybox-98bce',
    storageBucket: 'partybox-98bce.firebasestorage.app',
    iosBundleId: 'com.example.actionVerite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3t4cUdC7Mu_C0Zw2EfOpVrmVXcEMrtIo',
    appId: '1:779421460538:web:6c2123c9368cf270fbed03',
    messagingSenderId: '779421460538',
    projectId: 'partybox-98bce',
    authDomain: 'partybox-98bce.firebaseapp.com',
    storageBucket: 'partybox-98bce.firebasestorage.app',
  );
}
